# Generated by Django 4.2.7 on 2026-02-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='job_title',
            field=models.CharField(default='Software Developer', max_length=200),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(default='VIJAY MARTIN', max_length=200),
        ),
    ]
